# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
    
    - name: Checkout MASTER branch
      uses: actions/checkout@v2
      with:
        ref: 'main'
        fetch-depth: 0
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}  
    
    - run: echo Publish website!
    - run: git branch
    - run: npm ci
    - run: ls
    - run: npm run build --if-present
    - run: ls
    - run: git status
    - run: git add ./dist
    - run: git status
    - run: echo THE END
#    - name: Checkout PUBLISH branch
#      uses: actions/checkout@v2
#      with:
#       ref: 'publish'
#        fetch-depth: 0
#        clean: 'false'
#    - run: git checkout publish
#    - run: rm -rf ./*
#    - run: git branch
#    - run: ls
#    - run: git checkout master -- dist
#    - run: ls
#    - run: cd dist
#    - run: ls
