name: publish - Publish Website

on:
  push:
    branches: [ publish ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
    # Checkout "Publish" Branch
    - name: Checkout PUBLISH branch
      uses: actions/checkout@v2
      with:
        ref: 'publish'
        fetch-depth: 0
    # Deal with Git Config
    - name: Setup GitConfig
      uses: fregante/setup-git-user@v1
    # Append dummy text to a file
    # - run: echo "This is a test file $(date \"+%Y.%m.%d-%H.%M.%S\")" > ./branch.txt
    # Clean out unwanted files
    - run: |
        echo "Removing unwanted files and folders"
        rm -rf ./_site
        rm -rf ./plugins
        rm -f ./.eleventy.js
        rm -f ./branch.txt
        rm -f ./.gitattributes
        rm -f ./.gitignore
        rm -f ./package.json
        rm -f ./package-lock.json
        mv -v ./dist/* ./
        rm -rf ./dist
    # Create and push
    - run: |
        echo "Add and commit website back to publish branch"
        git add .
        git commit -m "New website build"
        git push   
